/** ****************************************************************************
  Copyright 2012 Progress Software Corporation
  
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
    http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
**************************************************************************** **/
/*------------------------------------------------------------------------
    File        : IApplicationStart
    Purpose     : Indicates that this is the first/main service to run in 
                  the application. This should be mapped to a concrete type
                  using InjectABL or some other scheme. 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Thu Apr 08 09:32:25 EDT 2010
    Notes       : 
  ----------------------------------------------------------------------*/

interface OpenEdge.CommonInfrastructure.Common.IApplicationStart: 
  
end interface.
