/*------------------------------------------------------------------------
    File        : ChildPresenter
    Purpose     : 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Wed Apr 07 14:49:54 EDT 2010
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.
using OpenEdge.Test.*.

routine-level on error undo, throw.

class OpenEdge.Test.ChildPresenter implements OpenEdge.Test.IChildPresenter: 

end class.