
/*------------------------------------------------------------------------
    File        : IMainPrimaryModel
    Purpose     : 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Wed Apr 07 14:27:24 EDT 2010
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

interface OpenEdge.Test.IMainPrimaryModel:  
  
end interface.