/*------------------------------------------------------------------------
    File        : MyUserControl
    Purpose     : 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Thu Apr 08 10:13:33 EDT 2010
    Notes       : 
  ----------------------------------------------------------------------*/
routine-level on error undo, throw.
  
using OpenEdge.Test.*.
using Progress.Lang.*.


class OpenEdge.Test.MyUserControl
        implements IChildView: 

end class.