
/*------------------------------------------------------------------------
    File        : IChildView
    Purpose     : 
    Syntax      : 
    Description : 
    @author pjudge
    Created     : Thu Apr 08 10:13:17 EDT 2010
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

interface OpenEdge.Test.IChildView:  
  
end interface.